#include <iostream>
#include <string>
using namespace std;

int main()
{
    while (true)
    {
        string ilu = "Anh yêu em bé mặp thúi nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo nhèoooooooooooooooooooooooooooooooooooooooooooooo";
        cout << ilu << endl;
    }
}